apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-1
  namespace: test-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: spring-1
  template:
    metadata:
      labels:
        app: spring-1
    spec:
      containers:
        - name: cont-1
          image: venkat956/spring-boot:1.0.0
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: svc-1
  namespace: test-ns    # <---- corrected namespace
spec:
  type: LoadBalancer
  selector:
    app: spring-1
  ports:
    - port: 8080
      targetPort: 8080
